-- Users table
CREATE TABLE sw_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) DEFAULT 'Manager'
);

-- Products table
CREATE TABLE sw_products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopify_id VARCHAR2(50),
  name VARCHAR2(255),
  cost_price NUMBER(10,2),
  selling_price NUMBER(10,2),
  stock NUMBER
);

-- Suppliers table
CREATE TABLE sw_suppliers (
  supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100),
  contact_info VARCHAR2(255)
);

-- Expenses table
CREATE TABLE sw_expenses (
  expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR2(50),
  amount NUMBER(10,2),
  expense_date DATE DEFAULT SYSDATE,
  description VARCHAR2(255)
);

-- Orders table
CREATE TABLE sw_orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopify_order_id VARCHAR2(50),
  product_id NUMBER,
  quantity NUMBER,
  selling_price NUMBER(10,2),
  order_date DATE
);
INSERT INTO sw_users (username, password_hash,role) VALUES ('Huzaifa', '$2b$10$2o.w5zPUnaTBjwD6wl/pn.EesqjvV1AuJYuzYP4w7kwtYjSUfXKBS','admin');
INSERT INTO sw_users (username, password_hash,role) VALUES ('Fahad', '$2b$10$8TIxCSLqJ7hIj1DekEONVetjuNxs5T0Woyg64AU2Lugb0g5Tf7uY2','admin');
commit;
select * FROM sw_users;
