-- Users table
CREATE TABLE sw_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) DEFAULT 'Manager'
);

-- Products table
CREATE TABLE sw_products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopify_id VARCHAR2(50),
  name VARCHAR2(255),
  cost_price NUMBER(10,2),
  selling_price NUMBER(10,2),
  stock NUMBER
);

-- Suppliers table
CREATE TABLE sw_suppliers (
  supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100),
  contact_info VARCHAR2(255)
);

-- Expenses table
CREATE TABLE sw_expenses (
  expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR2(50),
  amount NUMBER(10,2),
  expense_date DATE DEFAULT SYSDATE,
  description VARCHAR2(255)
);

-- Orders table
CREATE TABLE sw_orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopify_order_id VARCHAR2(50),
  product_id NUMBER,
  quantity NUMBER,
  selling_price NUMBER(10,2),
  order_date DATE
);

INSERT INTO sw_users (username, password_hash,role) VALUES ('Huzaifa', '$2b$10$3nKalsNuOrSHGoIV5pRGPefr7w07VX/yxH/bR1PyWZOriqCdUrab6','admin');
INSERT INTO sw_users (username, password_hash,role) VALUES ('Fahad', '$2b$10$UYLK.HYO.UbNbNlM3lJj6OjmB1AqQgX/0yfTJjDQFWadHCcZvghkO','admin');
commit;


CREATE TABLE sw_settings (
  id NUMBER PRIMARY KEY,
  store_name VARCHAR2(100),
  shopify_api_key VARCHAR2(255),
  shopify_api_secret VARCHAR2(255)
);

-- Insert default row with ID = 1
INSERT INTO sw_settings (id, store_name, shopify_api_key, shopify_api_secret)
VALUES (1, 'SeasonWize.pk', '', '');
